In [50]:
Name = ['Abdullai Mariam', 'Karim Mansura', 'Ibrahim Suleman', 'Mohammed Elham', 'Antwiwaa Elizabeth', 'Karim Mansur']
SS_Test_1 = [42.86, 38.57, 62.86, 38.57, 41.43, 48.57]

data_dict = {'Name': Name, 'Test_1(%)':SS_Test_1}

In [51]:
import pandas as pd
import numpy as np

In [52]:
df_Science = pd.DataFrame(data_dict, index = range (1, len(SS_Test_1) + 1))

In [53]:
df_Science

                 Name  Test_1(%)
1     Abdullai Mariam      42.86
2       Karim Mansura      38.57
3     Ibrahim Suleman      62.86
4      Mohammed Elham      38.57
5  Antwiwaa Elizabeth      41.43
6        Karim Mansur      48.57

In [54]:
df_Science.sort_values('Name',ascending = True, inplace = True)

In [55]:
df_Science

                 Name  Test_1(%)
1     Abdullai Mariam      42.86
5  Antwiwaa Elizabeth      41.43
3     Ibrahim Suleman      62.86
6        Karim Mansur      48.57
2       Karim Mansura      38.57
4      Mohammed Elham      38.57

In [56]:
new_index = np.arange(1, 7)

In [57]:
new_index

array([1, 2, 3, 4, 5, 6])

In [58]:
df_Science['Index'] = new_index

In [59]:
df_Science

                 Name  Test_1(%)  Index
1     Abdullai Mariam      42.86      1
5  Antwiwaa Elizabeth      41.43      2
3     Ibrahim Suleman      62.86      3
6        Karim Mansur      48.57      4
2       Karim Mansura      38.57      5
4      Mohammed Elham      38.57      6

In [60]:
df_Science.set_index('Index')

                     Name  Test_1(%)
Index
1         Abdullai Mariam      42.86
2      Antwiwaa Elizabeth      41.43
3         Ibrahim Suleman      62.86
4            Karim Mansur      48.57
5           Karim Mansura      38.57
6          Mohammed Elham      38.57

In [61]:
Name

['Abdullai Mariam',
 'Karim Mansura',
 'Ibrahim Suleman',
 'Mohammed Elham',
 'Antwiwaa Elizabeth',
 'Karim Mansur']

In [62]:
SS_Test_1 = [25.78, 14.84, 18.75, 13.28, 19.53, 10.94]

In [63]:
SS_Test_1

[25.78, 14.84, 18.75, 13.28, 19.53, 10.94]

In [64]:
data_dict = {'Name': Name, 'Test_1(%)':SS_Test_1}

In [65]:
df_Social_Studies = pd.DataFrame(data_dict, index=range(1, len(SS_Test_1) + 1))

In [66]:
df_Social_Studies

                 Name  Test_1(%)
1     Abdullai Mariam      25.78
2       Karim Mansura      14.84
3     Ibrahim Suleman      18.75
4      Mohammed Elham      13.28
5  Antwiwaa Elizabeth      19.53
6        Karim Mansur      10.94

In [67]:
df_Social_Studies.sort_values('Name',ascending = True, inplace = True)
df_Social_Studies

                 Name  Test_1(%)
1     Abdullai Mariam      25.78
5  Antwiwaa Elizabeth      19.53
3     Ibrahim Suleman      18.75
6        Karim Mansur      10.94
2       Karim Mansura      14.84
4      Mohammed Elham      13.28

In [68]:
new_index

array([1, 2, 3, 4, 5, 6])

In [69]:
df_Social_Studies['Index'] = new_index

In [70]:
df_Social_Studies

                 Name  Test_1(%)  Index
1     Abdullai Mariam      25.78      1
5  Antwiwaa Elizabeth      19.53      2
3     Ibrahim Suleman      18.75      3
6        Karim Mansur      10.94      4
2       Karim Mansura      14.84      5
4      Mohammed Elham      13.28      6

In [71]:
df_Social_Studies.set_index('Index', inplace=True)

In [72]:
df_Social_Studies

                     Name  Test_1(%)
Index
1         Abdullai Mariam      25.78
2      Antwiwaa Elizabeth      19.53
3         Ibrahim Suleman      18.75
4            Karim Mansur      10.94
5           Karim Mansura      14.84
6          Mohammed Elham      13.28

In [73]:
df_Science.set_index("Index", inplace=True)

In [74]:
df_Science

                     Name  Test_1(%)
Index
1         Abdullai Mariam      42.86
2      Antwiwaa Elizabeth      41.43
3         Ibrahim Suleman      62.86
4            Karim Mansur      48.57
5           Karim Mansura      38.57
6          Mohammed Elham      38.57

In [75]:
df_Social_Studies

                     Name  Test_1(%)
Index
1         Abdullai Mariam      25.78
2      Antwiwaa Elizabeth      19.53
3         Ibrahim Suleman      18.75
4            Karim Mansur      10.94
5           Karim Mansura      14.84
6          Mohammed Elham      13.28

In [76]:
df_Social_Studies.sum()

Name         Abdullai MariamAntwiwaa ElizabethIbrahim Sulem...
Test_1(%)                                               103.12
dtype: object

In [77]:
df_Science

                     Name  Test_1(%)
Index
1         Abdullai Mariam      42.86
2      Antwiwaa Elizabeth      41.43
3         Ibrahim Suleman      62.86
4            Karim Mansur      48.57
5           Karim Mansura      38.57
6          Mohammed Elham      38.57

In [78]:
df_Science

                     Name  Test_1(%)
Index
1         Abdullai Mariam      42.86
2      Antwiwaa Elizabeth      41.43
3         Ibrahim Suleman      62.86
4            Karim Mansur      48.57
5           Karim Mansura      38.57
6          Mohammed Elham      38.57

In [79]:
df_Science

                     Name  Test_1(%)
Index
1         Abdullai Mariam      42.86
2      Antwiwaa Elizabeth      41.43
3         Ibrahim Suleman      62.86
4            Karim Mansur      48.57
5           Karim Mansura      38.57
6          Mohammed Elham      38.57

In [80]:
df_Social_Studies

                     Name  Test_1(%)
Index
1         Abdullai Mariam      25.78
2      Antwiwaa Elizabeth      19.53
3         Ibrahim Suleman      18.75
4            Karim Mansur      10.94
5           Karim Mansura      14.84
6          Mohammed Elham      13.28